title: Sony Gallegos 
author_name: Sony Gallegos
email: sony.gallegos@gmail.com

twitter_username: sonygallegos
github_username: sonygallegos
linkedin_username: sonygallegos

social_links:
  - name: GitHub
    url: "https://github.com/sgallegos-dev"
  - name: LinkedIn
    url: "https://www.linkedin.com/in/sony-gallegos/"
  - name: Email
    url: "mailto:sony.gallegos@gmail.com"

description: > 
  Engineering Notes, Debug Logs && Technical Learnings 
baseurl: ""
url: "https://sgallegos-dev.github.io"
theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

header_pages:
  - about.md
  - knowledge.md
